Add ServiceURL option for KMS client
aws/amazon-s3-encryption-client-dotnet pull request #45
Opened 2023-08-07 01:30 UTC by bdurrani

AmazonKeyManagementServiceConfig doesn't use the service url when it's setting on AmazonS3CryptoConfigurationV2

## Description

## Motivation and Context
I'm using LocalStack when I set ServiceURL on AmazonS3CryptoConfigurationV2 I'm seeing the Kms calling aws endpoint

See #29 for reference

## Testing

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have read the **README** document
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

## License

- [ ] I confirm that this pull request can be released under the Apache 2 license

[issues]: https://github.com/aws/aws-sdk-net/issues
[license]: http://aws.amazon.com/apache2.0/
[cla]: http://en.wikipedia.org/wiki/Contributor_License_Agreement

2023-08-07 02:21 UTC, bdurrani commented
@normj Hi there
Is this change ok for the KMS client `ServiceURL` option?
As discussed here: https://github.com/aws/amazon-s3-encryption-client-dotnet/pull/29

Thanks

2023-08-10 20:10 UTC, ashovlin requested changes

2023-08-10 20:10 UTC, ashovlin commented on src/AmazonS3CryptoConfigurationBase.cs
> +        public AmazonKeyManagementServiceConfig KmsConfig { get; set; }
Could you add XML documentation to this, maybe something like:
```
/// <summary>
/// Configuration for the internal AWS Key Management Service client that will be used internally when encrypting S3 objects with KMS keys.
/// </summary>
/// <remarks>
/// If not specified here, the internal KMS client will inherit the region, timeout, and proxy configuration from the S3 configuration
/// </remarks>
```

2023-08-11 00:54 UTC, bdurrani commented on src/AmazonS3EncryptionClientBase.cs
> +                            }
I think this is what you were looking for? Let me know if misunderstood.

Thanks

2023-08-11 00:54 UTC, bdurrani commented on src/AmazonS3EncryptionClientBase.cs
> +                            }
I think this is what you were looking for? Let me know if misunderstood.

Thanks @ashovlin

2023-08-11 16:32 UTC, ashovlin approved these changes
Looks good to me, I'll line up a second reviewer from the internal team. We'll also handle the version bump once approved.

2023-08-11 17:29 UTC, dscpinheiro approved these changes

2023-08-17 00:54 UTC, merged

2023-08-17 00:54 UTC, ashovlin commented
I've merged this to `dev`, which is our staging branch for the next release. We'll reply again once the new release is out.

2023-08-18 13:38 UTC, ashovlin commented
This PR was released yesterday in [2.1.0](https://www.nuget.org/packages/Amazon.Extensions.S3.Encryption/2.1.0), thanks again for your contribution!